sudo: required

services: docker

before_install:
  - dcoker login -u noriyoshimaeda -p dckr_pat_dQPVJhHFxgILV9c-HnKkQ5fmxW4
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test